### ISSUE TITLE
这个工具写得很好，不过有一点不好的希望可以将输出的html属性将单引号包裹改成双引号

### ISSUE THREAD

**Issue by wztscau** [zhongjiajian/wxml-to-uni#1]
希望改完后发布到npm，谢谢

**Comment by zhongjiajian** [comment]
谢谢，已经改了一部分，但是无法全改，因为使用到了一个叫himalaya的npm包，使用单引号是这个npm包写死的（没提供配置参数）。
另外可以使用写xml格式化插件看看，把单引号改成双引号。

**Comment by zhongjiajian** [comment]
> 希望改完后发布到npm，谢谢

谢谢，已经改了一部分，但是无法全改，因为使用到了一个叫himalaya的npm包，使用单引号是这个npm包写死的（没提供配置参数）。
另外可以使用写xml格式化插件看看，把单引号改成双引号。
